apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: artifactory
    meta.helm.sh/release-namespace: artifactory
  creationTimestamp: "2025-05-16T09:32:22Z"
  labels:
    app: artifactory
    app.kubernetes.io/managed-by: Helm
    chart: artifactory-107.111.7
    heritage: Helm
    release: artifactory
  name: artifactory-configmaps
  namespace: artifactory
  resourceVersion: "88946"
  uid: 121930e8-1827-4155-9e71-53c0e84e7490
