apiVersion: v1
data:
  master-key: NzYxZDE2YjVjMTVhMDZmNjc5NWI5M2VlODIzOWExNTk3YTRkMWI1NWIxYWJlOTJlZTNjMTkxZWY5MjMwN2ZkZQ==
kind: Secret
metadata:
  creationTimestamp: "2025-05-16T09:29:28Z"
  name: my-masterkey-secret
  namespace: artifactory
  resourceVersion: "88701"
  uid: 213bf649-cf2e-43c1-b04c-2601e2b40505
type: Opaque
