apiVersion: v1
data:
  password: UlVTWHBsYlhLaA==
  postgres-password: QWtoaGVYemtCOA==
kind: Secret
metadata:
  annotations:
    meta.helm.sh/release-name: artifactory
    meta.helm.sh/release-namespace: artifactory
  creationTimestamp: "2025-05-16T09:32:22Z"
  labels:
    app.kubernetes.io/instance: artifactory
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/version: 16.3.0
    helm.sh/chart: postgresql-15.5.20
  name: artifactory-postgresql
  namespace: artifactory
  resourceVersion: "88942"
  uid: 53c6e528-df66-401d-8319-44e5dd709681
type: Opaque
